const SEED_BOOKS = [
  {
    id: "b001",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    year: 2018,
    pages: 320,
    rating: 4.8,
    cover: "images/books/atomic-habits.png",
    description: "A practical, research-backed guide to building good habits and breaking bad ones through small, incremental changes.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b002",
    title: "1984",
    author: "George Orwell",
    genre: "Fiction",
    year: 1949,
    pages: 328,
    rating: 4.7,
    cover: "images/books/1984.png",
    description: "A dystopian classic depicting a totalitarian regime that controls truth, language, and thought itself.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b003",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    year: 1925,
    pages: 180,
    rating: 4.3,
    cover: "images/books/gatsby.png",
    description: "A tragic tale of wealth, love, and the elusive American Dream set in the Jazz Age.",
    status: "borrowed",
    borrowedDate: "2026-06-25",
    dueDate: "2026-07-09"
  },
  {
    id: "b004",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    year: 2011,
    pages: 443,
    rating: 4.6,
    cover: "images/books/sapiens.png",
    description: "An exploration of how Homo sapiens came to dominate the world, tracing cognitive, agricultural, and scientific revolutions.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b005",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1937,
    pages: 310,
    rating: 4.7,
    cover: "images/books/hobbit.png",
    description: "Bilbo Baggins is swept into an epic quest to reclaim a stolen dwarf kingdom from a fearsome dragon.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b006",
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Technology",
    year: 2008,
    pages: 464,
    rating: 4.4,
    cover: "images/books/clean-code.png",
    description: "A handbook of agile software craftsmanship, teaching principles and practices for writing readable, maintainable code.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b007",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    genre: "Non-Fiction",
    year: 2020,
    pages: 256,
    rating: 4.7,
    cover: "images/books/psychology-of-money.png",
    description: "Timeless lessons on wealth, greed, and happiness, exploring how people actually think about money.",
    status: "borrowed",
    borrowedDate: "2026-06-30",
    dueDate: "2026-07-14"
  },
  {
    id: "b008",
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    year: 1965,
    pages: 412,
    rating: 4.8,
    cover: "images/books/dune.png",
    description: "A sweeping saga of politics, religion, and ecology on the desert planet Arrakis, the galaxy's only source of the spice melange.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b009",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 1997,
    pages: 309,
    rating: 4.9,
    cover: "images/books/harry-potter.png",
    description: "An orphaned boy discovers he is a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b010",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "Non-Fiction",
    year: 2011,
    pages: 499,
    rating: 4.5,
    cover: "images/books/thinking-fast-slow.png",
    description: "A Nobel laureate's exploration of the two systems that drive the way we think — one fast and intuitive, one slow and deliberate.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b011",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    year: 1813,
    pages: 279,
    rating: 4.6,
    cover: "images/books/pride-prejudice.png",
    description: "A witty exploration of manners, marriage, and morality in Georgian England, centered on the spirited Elizabeth Bennet.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  },
  {
    id: "b012",
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Fiction",
    year: 1988,
    pages: 208,
    rating: 4.4,
    cover: "images/books/alchemist.png",
    description: "A shepherd boy travels from Spain to Egypt in search of treasure, discovering the meaning of his own 'Personal Legend' along the way.",
    status: "available",
    borrowedDate: null,
    dueDate: null
  }
];
